//@version=5
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// Developer: John EHLERS
// based on script by © KivancOzbilgic
indicator('Laguerre RSI', shorttitle='LaRSI', overlay=false)

var g_laguerre= "LaGuerre"
src = input(title='Source', defval=close, group=g_laguerre)
alpha = input.float(title='Alpha', minval=0, maxval=1, step=0.1, defval=0.2, group=g_laguerre)
colorchange = input(title='Change Color ?', defval=false, group=g_laguerre)

maLength = input.int(20, "K", minval=1)
rsiLength = input.int(13, "D", minval=1)

ma20 = ta.sma(close, maLength)
rsiMA20 = ta.rsi(ma20, rsiLength)

rsiMA20Bullish = ta.rising(rsiMA20, 1)
rsiMA20Bearish = ta.falling(rsiMA20, 1)

var g_tsv = "TSV"

l = input(13, title='TSV Length')
l_ma = input(20, title='MA Length')
l_ma_short = input(14, title='MA Length')

t = math.sum(close > close[1] ? volume * (close - close[1]) : close < close[1] ? volume * (close - close[1]) : 0, l)
m = ta.ema(t, l_ma)
m2 = ta.ema(t, l_ma_short)

tsvBullish = m2 > m
tsvBearish = m2 < m

f_stochrsi(src, lengthRSI) =>
    rsi = ta.rsi(src, lengthRSI)
    k = ta.sma(ta.stoch(rsi, rsi, rsi, lengthRSI), 3)
    d = ta.sma(k, 3)
    [k, d]

[stochK, stochD] = f_stochrsi(close, 14)

f_laRsi(src, alpha) =>
    gamma = 1 - alpha
    L0 = 0.0
    L0 := (1 - gamma) * src + gamma * nz(L0[1])
    L1 = 0.0
    L1 := -gamma * L0 + nz(L0[1]) + gamma * nz(L1[1])

    L2 = 0.0
    L2 := -gamma * L1 + nz(L1[1]) + gamma * nz(L2[1])

    L3 = 0.0
    L3 := -gamma * L2 + nz(L2[1]) + gamma * nz(L3[1])

    cu = (L0 > L1 ? L0 - L1 : 0) + (L1 > L2 ? L1 - L2 : 0) + (L2 > L3 ? L2 - L3 : 0)

    cd = (L0 < L1 ? L1 - L0 : 0) + (L1 < L2 ? L2 - L1 : 0) + (L2 < L3 ? L3 - L2 : 0)

    temp = cu + cd == 0 ? -1 : cu + cd
    LaRSI = temp == -1 ? 0 : cu / temp
    LaRSI

LaRSI = f_laRsi(src, alpha)

LaRSI12m = request.security(syminfo.tickerid, '12', f_laRsi(close, alpha))
LaRSI45m = request.security(syminfo.tickerid, '45', f_laRsi(close, alpha))
LaRSI3h = request.security(syminfo.tickerid, '180', f_laRsi(close, alpha))
LaRSI6h = request.security(syminfo.tickerid, '360', f_laRsi(close, alpha))
LaRSI12h = request.security(syminfo.tickerid, '720', f_laRsi(close, alpha))
LaRSI1d = request.security(syminfo.tickerid, '1440', f_laRsi(close, alpha))
LaRSI3d = request.security(syminfo.tickerid, '3D', f_laRsi(close, alpha))
LaRSI1w = request.security(syminfo.tickerid, '1W', f_laRsi(close, alpha))

minBullish = 20.0
minBearish = 80.0
if timeframe.isminutes and timeframe.multiplier > 180
    minBullish := 40.0
    minBearish := 60.0

isBullish = (100 * LaRSI < minBullish)
isBearish = (100 * LaRSI > minBearish)

if timeframe.isminutes
    if timeframe.multiplier <= 60
        isBullish := isBullish and rsiMA20 < 5
        isBearish := isBearish and rsiMA20 > 95

    if timeframe.multiplier < 180
        isBullish := isBullish and ((LaRSI3h * 100) < 20 or (ta.rising(LaRSI3h, 1) and (LaRSI3h * 100) < 80))
        isBearish := isBearish and ((LaRSI3h * 100) > 50 or (ta.falling(LaRSI3h, 1) and (LaRSI3h * 100) > 20))
    else if timeframe.multiplier < 360
        isBullish := isBullish and ((LaRSI6h * 100) < 40 or (ta.rising(LaRSI6h, 1) and (LaRSI6h * 100) < 80))
        isBearish := isBearish and ((LaRSI6h * 100) > 50 or (ta.falling(LaRSI6h, 1) and (LaRSI6h * 100) > 20))

    if timeframe.multiplier > 180
        isBullish := isBullish and (m2 > m or ta.rising(m, 1))
        isBearish := isBearish and (m2 < m or ta.falling(m, 1))

    if timeframe.multiplier > 180 and timeframe.multiplier < 720
        isBullish := isBullish and ((LaRSI6h * 100) < 40 or (ta.rising(LaRSI6h, 1) and (LaRSI6h * 100) < 80))
        isBearish := isBearish and ((LaRSI6h * 100) > 50 or (ta.falling(LaRSI6h, 1) and (LaRSI6h * 100) > 20))

bullishOpacity = isBullish ? 80 : 100
bearishOpacity = isBearish ? 80 : 100

tsvPivotUp = ta.crossover(m2, m)
tsvPivotDown = ta.crossunder(m2, m)

stochPivotUp = ta.rising(stochD, 1) and not ta.rising(stochD, 2) and stochD < 60
stochPivotDown = ta.falling(stochD, 1) and not ta.falling(stochD, 2) and stochD > 40

buyEntrySignal = (stochPivotUp or tsvPivotUp) and isBullish
sellEntrySignal = (stochPivotDown or tsvPivotDown) and isBearish

bgColor = isBearish ? color.new(color.red, bearishOpacity) : isBullish ? color.new(color.green, bullishOpacity) : na

min = plot(0.0, title="Min", color=color.new(color.white, 90), linewidth=1)
max = plot(100.0, title="Max", color=color.new(color.white, 90), linewidth=1)

fill(min, max, title = "Background", color = bgColor, title='Fill')

Color = colorchange ? LaRSI > LaRSI[1] ? color.green : color.red : color.yellow
plot(100 * LaRSI, title='LaRSI', linewidth=2, color=Color, transp=0)
plot(10, linewidth=1, color=color.new(color.white, 50))
plot(90, linewidth=1, color=color.new(color.white, 50))

plotshape(buyEntrySignal ? -10 : na, title="Long", style=shape.diamond, color=color.green, location=location.absolute, size = size.small)
plotshape(sellEntrySignal ? 110 : na, title="Short", style=shape.diamond, color=color.red, location=location.absolute, size = size.small)

alertcondition(buyEntrySignal, 'LaGuerre LONG', 'LaGuerre LONG')
alertcondition(sellEntrySignal, 'LaGuerre SHORT', 'LaGuerre SHORT')